### ISSUE TITLE
RichEmbed can be disabled by end users.

### ISSUE THREAD

**Issue by ap4gh** [GitCodeCareer/discord-bot#13]
---
about: "Use text instead of RichEmbed"
---

I see that for many commands bot responds with a RichEmbed. I have disabled link previews on my discordapp, so whenever the bot sends a RichEmbed formatted message I see nothing. My general suggestion is to **remove RE and replace it with either code block or normal text**.

Read more about this issue here: https://anidiots.guide/first-bot/using-embeds-in-messages

**Comment by crock** [comment]
Didn’t realize this was a problem. i guess I should assume hat people might actually disable link previews. To be honest, Discord should make link previews separate from embeds. 

I will find a nice way to portray the same info in text as well. We can embeds as a way to optionally enhance the output.

**Comment by ap4gh** [comment]
The info sent to user via DMs should be pure text and the one sent on the current channel can be both embed and text.

**Comment by ap4gh** [comment]
I am closing this issue as there is no perfect solution for this short coming at this moment.
